services:
  app:
    env_file:
      - ./src/.env
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: university/laravel-app:latest
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html:delegated
      - ./src/public/build:/var/www/html/public/build:rw
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    container_name: laravel_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge